@PORT = 7777
@TOKEN = bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOjEsImlhdCI6MTU4NDExMDk2NiwiZXhwIjoxNTg0MTk3MzY2fQ.jJmb4DCXljVoWPUM7urB8oA5mJQSjCh0vx8smMHWnFc
@BLOG_ID = 1

###

POST http://localhost:{{PORT}}/api/blogs
content-type: application/json
Authorization: {{TOKEN}}

{
    "title": "Second Post by Admin",
    "content": "This is the actual post body, Im just without imagination"
}

###

GET http://localhost:{{PORT}}/api/blogs
Authorization: {{TOKEN}}

###

GET http://localhost:{{PORT}}/api/blogs/{{BLOG_ID}}
Authorization: {{TOKEN}}

###

PUT http://localhost:{{PORT}}/api/blogs/{{BLOG_ID}}
content-type: application/json
Authorization: {{TOKEN}}

{
    "title": "First Post that was edited a third time",
    "content": "This is the actual post body, Im just without imagination"
}


###

DELETE http://localhost:{{PORT}}/api/blogs/{{BLOG_ID}}
Authorization: {{TOKEN}}

