@PORT = 7777
@TOKEN = bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOjEsImlhdCI6MTU4NDU2ODUxMywiZXhwIjoxNTg0NjU0OTEzfQ.FwpVh5sZnHzODR69Funic-T1Hx8Umb9SLStdV5PxFBw
@BLOG_ID = 4

###

POST http://localhost:{{PORT}}/api/blogs
content-type: application/json
Authorization: {{TOKEN}}

{
    "title": "Test Post of JWT auth",
    "content": "This is the actual post body, Im just without imagination"
}

###

GET http://localhost:{{PORT}}/api/blogs
Authorization: {{TOKEN}}

###

GET http://localhost:{{PORT}}/api/blogs/{{BLOG_ID}}
Authorization: {{TOKEN}}

###

PUT http://localhost:{{PORT}}/api/blogs/{{BLOG_ID}}
content-type: application/json
Authorization: {{TOKEN}}

{
    "title": "First Post that was edited a third time",
    "content": "This is the actual post body, Im just without imagination"
}


###

DELETE http://localhost:{{PORT}}/api/blogs/{{BLOG_ID}}
Authorization: {{TOKEN}}

