@PORT = 7777
@BEARER_TOKEN=bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOjEsImlhdCI6MTU4NDM4MzU3NSwiZXhwIjoxNTg0NDY5OTc1fQ.gPDsx2Rs_qVp8NK8NUz44E4hJswdyHHXKEE5Jb5_yGc

POST http://localhost:{{PORT}}/api/users
Content-Type: application/json

{
    "username": "admin",
    "email": "admin@admin.com",
    "password": "12345678"
}

###


GET http://localhost:{{PORT}}/api/users
Authorization: {{BEARER_TOKEN}}


###

DELETE  http://localhost:{{PORT}}/api/users/
Authorization: {{BEARER_TOKEN}}